version: '3.4'

services:
  culinary-assistant-main:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
    ports:
      - "5000:5000"

  culinary-assistant-images:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5002
    ports:
      - "5002:5002"

  culinary-assistant-notifications:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5003
    ports:
      - "5003:5003"
